### ISSUE TITLE
question about CMAKE_PREFIX_PATH for pytorch 

### ISSUE THREAD

**Issue by amiltonwong** [jiexiong2016/GCNv2_SLAM#1]
Hi, @jiexiong2016 ,

According to [build.sh](https://github.com/jiexiong2016/GCNv2_SLAM/blob/master/build.sh#L28), CMAKE_PREFIX_PATH should be set pointing to pytorch lib location. Would you provide an example for it?
For example, my pytorch is installed at `/root/anaconda3/envs/pytorch1.0/lib/python3.6/site-packages/torch/lib`.

THX!

**Comment by jiexiong2016** [comment]
Hi,
The CMAKE_PREFIX_PATH should be pointed to the libtorch (c++ library of pytorch). You can build libtorch locally by:
`git clone --recursive -b v1.0.1 https://github.com/pytorch/pytorch
cd pytorch && mkdir build && cd build
python ../tools/build_libtorch.py`
Then the path in this case is "pytorch/torch/lib/tmp_install/". We will add the example to readme file.
