### ISSUE TITLE
build.sh error

### ISSUE THREAD

**Issue by ytgcljj** [jiexiong2016/GCNv2_SLAM#14]
/home/launchx-500-10802/github/GCNv2_SLAM/src/ORBmatcher.cc:32:34: fatal error: opencv2/features2d.hpp: 没有那个文件或目录
compilation terminated.
CMakeFiles/ORB_SLAM2.dir/build.make:206: recipe for target 'CMakeFiles/ORB_SLAM2.dir/src/ORBmatcher.cc.o' failed
make[2]: *** [CMakeFiles/ORB_SLAM2.dir/src/ORBmatcher.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
/home/launchx-500-10802/github/GCNv2_SLAM/src/GCNextractor.cc: In function ‘void ORB_SLAM2::nms(cv::Mat, cv::Mat, std::vector<cv::KeyPoint>&, cv::Mat&, int, int, int, int)’:
/home/launchx-500-10802/github/GCNv2_SLAM/src/GCNextractor.cc:96:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < pts_raw.size(); i++)
                       ^
/home/launchx-500-10802/github/GCNv2_SLAM/src/GCNextractor.cc:107:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < pts_raw.size(); i++)
                       ^
/home/launchx-500-10802/github/GCNv2_SLAM/src/GCNextractor.cc:148:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i=0; i<select_indice.size(); i++)
                    ^
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/ORB_SLAM2.dir/all' failed
make[1]: *** [CMakeFiles/ORB_SLAM2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by jiexiong2016** [comment]
You probably need to check whether you correctly installed opencv.
