### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ytgcljj** [jiexiong2016/GCNv2_SLAM#15]
launchx-500-10802@launchx50010802:~/github/GCNv2_SLAM/GCN2$ ./rgbd_gcn ../Vocabulary/GCNvoc.bin TUM3.yaml /home/launchx-500-10802/github/rgbd_dataset_freiburg3_long_office_household_validation /home/launchx-500-10802/github/rgbd_dataset_freiburg3_long_office_household_validation/associations.txt
./rgbd_gcn: /home/launchx-500-10802/anaconda3/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /home/launchx-500-10802/github/pytorch/torch/lib/libcaffe2.so)
./rgbd_gcn: /home/launchx-500-10802/anaconda3/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /opt/OpenBLAS/lib/libopenblas.so.0)
./rgbd_gcn: /home/launchx-500-10802/anaconda3/lib/libgomp.so.1: version `GOMP_4.0' not found (required by /usr/lib/x86_64-linux-gnu/libsoxr.so.0)

**Comment by jiexiong2016** [comment]
It is likely due to the pytorch is not properly linked. Hard to give any suggestion as it depends too much on how the dependencies are installed. I could only suggest to check pytorch github issues for possible solution for this. Closed for now.
