### ISSUE TITLE
GCNExtraction breaks after frame #18

### ISSUE THREAD

**Issue by chaiein** [jiexiong2016/GCNv2_SLAM#17]
Program execution breaks at module = torch::jit::load(net_fn); in GCNExtractor.cc. 

net_fn has the value gcn2.pt. 
Why is it breaking at frame #18 and what is the program doing with previous frames that is different at frame #18? I am performing Monocular tracking.

**Comment by jiexiong2016** [comment]
It is currently not supporting the monocular SLAM yet. Are you testing with your customized code?

**Comment by jiexiong2016** [comment]
Cannot reproduce this error.
