### ISSUE TITLE
Could the GCNv2 network forward with a single RGB frame?

### ISSUE THREAD

**Issue by siyuada** [jiexiong2016/GCNv2_SLAM#23]
Thanks for sharing this nice work!

In the paper, the only place you mentioned depth information is in eq. 3, to find correct correspondence. I wonder could I just passed a single RGB frame to get keypoints and descriptions into network while in inference time？

Thanks！

**Comment by jiexiong2016** [comment]
Hi,
The GCNv2 is using a single RGB frame and original GCN is using a pair of consecutive RGB frames.

**Comment by siyuada** [comment]
Thanks for reply~
