### ISSUE TITLE
你好，不知道是我的pytorch装错了还是路径有问题？

### ISSUE THREAD

**Issue by 450932894** [jiexiong2016/GCNv2_SLAM#24]
CMake Error at CMakeLists.txt:48 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/tang/GCNv2_SLAM/build/CMakeFiles/CMakeOutput.log".
make: *** 没有指明目标并且找不到 makefile。 停止。

**Comment by 450932894** [comment]
请问你这个时无GPU版的pytorch么

**Comment by 450932894** [comment]
@jiexiong2016

**Comment by 450932894** [comment]
我想问下pytorch的版本问题？ Pytorch C++ api(libtorch)     和 Download here: 
https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip   是一个版本么

**Comment by jiexiong2016** [comment]
这个应该是路径问题，如果想用最新的api可以试一下[nightly build version](https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-latest.zip)。 我装的pytorch是直接从mater brach local build的。

**Comment by ChLee98** [comment]
> CMake Error at CMakeLists.txt:48 (find_package):
> By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
> asked CMake to find a package configuration file provided by "Torch", but
> CMake did not find one.
> 
> Could not find a package configuration file provided by "Torch" with any of
> the following names:
> 
> ```
> TorchConfig.cmake
> torch-config.cmake
> ```
> 
> Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
> "Torch_DIR" to a directory containing one of the above files. If "Torch"
> provides a separate development package or SDK, be sure it has been
> installed.
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/tang/GCNv2_SLAM/build/CMakeFiles/CMakeOutput.log".
> make: *** 没有指明目标并且找不到 makefile。 停止。

我也遇到了这个问题，请问您最后怎么解决的呢？

**Comment by sunpeng981712364** [comment]
在CmakeList.txt 中行首加上

**Comment by sunpeng981712364** [comment]
In my case, adding these two lines at the beginning of GCNv2_SLAM/CMakeLists.txt solved the problem. Please modify the /path_to_your_torch/ part.

set(Caffe2_DIR "/path_to_your_torch/pytorch/torch/lib/tmp_install/share/cmake/Caffe2/")
include_directories("path_to_your_torch/pytorch/torch/lib/include")
