### ISSUE TITLE
A small question about paper

### ISSUE THREAD

**Issue by kxhit** [jiexiong2016/GCNv2_SLAM#4]
Thanks for sharing this nice work!
![GCN2-Q1](https://user-images.githubusercontent.com/16812362/54738276-84927080-4bee-11e9-950e-c9690dbb2529.png)

I have a question about the expression "if abs(xnj − xi) < c " at line 4 in the Algorithm 1 in paper "GCNv2: Efficient Correspondence Prediction for Real-Time SLAM, J. Tang, L. Ericson, J. Folkesson and P. Jensfelt, in arXiv:1902.11046, 2019". 
I think the "<" should be ">", because we want to tolerate the noise caused by imperfect camera calibration and ground truth. So we will not use points within "c" threshold (e.g c = 5 pixel) as negative samples, which are very likely to be the bias caused by noise.
Am I correct? Is this a typo mistake or am I getting it wrong? Waiting for your reply! Thanks!

**Comment by jiexiong2016** [comment]
@kxhit Sorry for the mistake! This is a typo, it should be ">". Thank a lot for pointing out!

**Comment by kxhit** [comment]
@jiexiong2016 Thank you for your prompt reply! Closed.
