### ISSUE TITLE
feature detection and match performance of GCNV2

### ISSUE THREAD

**Issue by TBetterman** [jiexiong2016/GCNv2_SLAM#51]
![image](https://user-images.githubusercontent.com/12430411/98333500-d7c36c00-203b-11eb-971f-2782353164df.png)
Hi，i test GCNV2 detection and matching performance on two image with a certain parallax(not too large)，although the features detected are evenly distributed, the match result is not good. Some corner point which can be matched use ORB(for example: corner points on square tiles), but GCNV2 seems can not match correctly. And, observing the matching result above, the feature points on the matching do not seem to be very stable features (such as the features of the edge of the line, the features on the ground)

bellow is detection and matching result(test on two image with large parallax):
![image](https://user-images.githubusercontent.com/12430411/98334008-e8281680-203c-11eb-89ff-52436eef45c2.png)

**Comment by zzl20** [comment]
你好我自己测试了一下，遇到好多特征点在白墙或者不像特征点的地方你遇到了吗，还是这就是这样子的啊
