### ISSUE TITLE
can you tell me,what's this,the number below the "New map created with 287 points"

### ISSUE THREAD

**Issue by wkwukai** [jiexiong2016/GCNv2_SLAM#7]
![Screenshot from 2019-03-22 17-05-16](https://user-images.githubusercontent.com/37244421/54811969-f63cee00-4cc4-11e9-9bb8-770e464ee8e8.png)

**Comment by jiexiong2016** [comment]
Hello, we cannot reproduce this issue. The code doesn't include the printing of numbers as you mentioned.

**Comment by wkwukai** [comment]
ok,thankyou
